FAT2_156_add_search_by_postcode
SkillsFundingAgency/das-location-api pull request #3
Opened 2020-09-09 12:54 UTC by robyoung91

2020-09-09 14:33 UTC, PeterDavidWilliams requested changes

2020-09-09 14:33 UTC, PeterDavidWilliams commented on src/SFA.DAS.Location.Application.UnitTests/Search/Queries/WhenHandlingTheSearchLocationRequest.cs
> +        [Test, MoqInlineAutoData("Man")]
Is this test case necessary? Looking at the test, it looks like it _should_ work without setting the search term

2020-09-09 15:01 UTC, PeterDavidWilliams approved these changes

2020-09-09 16:57 UTC, dashton82 requested changes

2020-09-09 16:57 UTC, dashton82 commented on src/SFA.DAS.Location.Domain/Interfaces/IPostcodeApiService.cs
> +        Task<IEnumerable<SuggestedLocation>> GetAllStartingWithOutcode(string query, int resultCount = 10);
Not sure we need a default here for the result count - its defaulted on the controller action as well

2020-09-09 16:57 UTC, dashton82 commented on src/SFA.DAS.Location.Infrastructure.UnitTests/ApiClient/WhenGettingDataFromPostcodeIO.cs
> +    }
Missing a test case for the notfound response and returning null - I'd also split out the two methods under test into separate test files

2020-09-09 16:57 UTC, dashton82 commented on src/SFA.DAS.Location.Domain/Models/SuggestedLocation.cs
> +        public static implicit operator SuggestedLocation(Domain.Entities.Location source)
Doesn't appear to be a test for this mapping

2020-09-10 13:42 UTC, dashton82 approved these changes

2020-09-14 10:28 UTC, merged